'use client'

import { useEffect, useMemo, useRef, useState } from 'react'
import { CalendarDays, Check, ChevronLeft, ChevronRight, Clock3, Dice5, Download, Eye, EyeOff, FileUp, GraduationCap, ImagePlus, Menu, Moon, MoreHorizontal, Pencil, Play, Plus, RotateCcw, Settings2, Sun, Target, Trash2, Pause, X } from 'lucide-react'

type Module = { id: string; short: string; name: string; color: string }
type Block = { id: string; day: number; start: string; end: string; module: string; topic: string; notes?: string; done?: boolean; locked?: boolean }
type Deadline = { id: string; module: string; title: string; date: string; kind: string }
type InstallPromptEvent = Event & { prompt: () => Promise<void>; userChoice: Promise<{ outcome: 'accepted' | 'dismissed' }> }

const DASH_LOGO = <svg viewBox="0 0 32 32" aria-hidden="true"><path d="M8 5h8.5C22.85 5 27 9.15 27 16s-4.15 11-10.5 11H8V5Zm7.5 17c3.4 0 5.5-2.15 5.5-6s-2.1-6-5.5-6H14v12h1.5Z" fill="currentColor" /></svg>

const MODULES: Module[] = [
  { id: 'osc', short: 'OSC', name: 'Operating Systems Concepts', color: '#be4d5e' },
  { id: 'fis', short: 'FIS', name: 'Introduction to Information System Security', color: '#c08a2e' },
  { id: 'bcs', short: 'BCS', name: 'Basics for Corporate Security and Risk Management', color: '#2f8a5b' },
  { id: 'cyber', short: 'Cybercrime', name: 'Cybercrime and Society', color: '#3b6fb0' },
  { id: 'ics', short: 'ICS', name: 'Introduction to Computer in Cyber Security', color: '#1d8a9e' },
  { id: 'ctw', short: 'CTW', name: 'Communication and Technical Writing', color: '#a8479e' },
]
const DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const HOURS = Array.from({ length: 15 }, (_, i) => i + 7)
const pad = (n: number) => String(n).padStart(2, '0')
const todayIndex = (new Date().getDay() + 6) % 7
const todayLabel = new Date().toLocaleDateString('en-GB', { weekday: 'long', day: 'numeric', month: 'long' })

function block(id: string, day: number, start: string, end: string, module: string, topic: string, locked = false): Block { return { id, day, start, end, module, topic, locked } }
const DEFAULT_BLOCKS: Block[] = [
  block('class-mon', 0, '09:00', '11:00', 'class', 'Class · fixed', true), block('class-tue', 1, '14:00', '17:00', 'class', 'Class · fixed', true), block('class-wed', 2, '15:00', '17:00', 'class', 'Lesson · fixed', true),
  block('mon-osc', 0, '13:00', '14:30', 'osc', 'Processes & scheduling'), block('mon-ics', 0, '15:30', '16:30', 'ics', 'Security foundations'), block('tue-ctw', 1, '19:00', '20:30', 'ctw', 'Academic writing'),
  block('wed-osc', 2, '09:00', '11:00', 'osc', 'Memory management'), block('wed-fis', 2, '11:15', '12:15', 'fis', 'Threat modelling'), block('wed-bcs', 2, '19:00', '20:00', 'bcs', 'Risk registers'), block('thu-osc', 3, '09:00', '11:00', 'osc', 'File systems'), block('thu-fis', 3, '11:15', '12:45', 'fis', 'Access control'), block('thu-bcs', 3, '14:00', '15:30', 'bcs', 'Corporate controls'), block('fri-osc', 4, '09:00', '11:00', 'osc', 'Mock questions'), block('fri-cyber', 4, '11:15', '12:30', 'cyber', 'Digital evidence'), block('fri-ctw', 4, '14:00', '15:00', 'ctw', 'Presentation outline'), block('sat-osc', 5, '09:00', '11:00', 'osc', 'Weakest module mock test'), block('sat-ics', 5, '11:15', '12:15', 'ics', 'Revision sprint'), block('sun-recap', 6, '10:00', '11:30', 'all', 'Weekly recap · all modules'),
]

function initialDeadlines(): Deadline[] { const d = new Date(); const add = (days: number) => { const x = new Date(d); x.setDate(x.getDate() + days); return x.toISOString().slice(0, 10) }; return [{ id: 'd1', module: 'osc', title: 'OSC exam', date: add(21), kind: 'Exam' }, { id: 'd2', module: 'fis', title: 'FIS assignment', date: add(10), kind: 'Assignment' }, { id: 'd3', module: 'bcs', title: 'BCS exam', date: add(28), kind: 'Exam' }] }

export default function Page() {
  const [blocks, setBlocks] = useState<Block[]>(DEFAULT_BLOCKS)
  const [deadlines, setDeadlines] = useState<Deadline[]>(initialDeadlines)
  const [view, setView] = useState<'week' | 'day' | 'deadlines' | 'modules' | 'exam' | 'settings'>('week')
  const [day, setDay] = useState(todayIndex)
  const [editMode, setEditMode] = useState(false)
  const [hiddenModules, setHiddenModules] = useState<string[]>([])
  const [examName, setExamName] = useState('Final exam prep')
  const [examDate, setExamDate] = useState(() => { const d = new Date(); d.setDate(d.getDate() + 21); return d.toISOString().slice(0, 10) })
  const [examFocus, setExamFocus] = useState('OSC, FIS, BCS')
  const [modal, setModal] = useState<Block | null | undefined>(undefined)
  const [theme, setTheme] = useState<'light' | 'dark'>('light')
  const [menuOpen, setMenuOpen] = useState(false)
  const [now, setNow] = useState(new Date())
  const [installPrompt, setInstallPrompt] = useState<InstallPromptEvent | null>(null)
  const [installed, setInstalled] = useState(false)
  const [backgroundImage, setBackgroundImage] = useState('')
  const [transparency, setTransparency] = useState(72)
  const [settingsOpen, setSettingsOpen] = useState(false)
  const [pomodoroHours, setPomodoroHours] = useState(1)
  const fileInputRef = useRef<HTMLInputElement>(null)
  const [pomodoroSeconds, setPomodoroSeconds] = useState(0)
  const [pomodoroRunning, setPomodoroRunning] = useState(false)
  const pomodoroStarted = pomodoroSeconds > 0 || pomodoroRunning

  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('mathata-fr') || '{}'); if (saved.blocks) setBlocks(saved.blocks); if (saved.deadlines) setDeadlines(saved.deadlines); if (saved.theme) setTheme(saved.theme); if (saved.backgroundImage) setBackgroundImage(saved.backgroundImage) } catch { setBlocks(DEFAULT_BLOCKS) } }, [])
  useEffect(() => {
    const onBeforeInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as InstallPromptEvent) }
    const onInstalled = () => { setInstalled(true); setInstallPrompt(null) }
    window.addEventListener('beforeinstallprompt', onBeforeInstall)
    window.addEventListener('appinstalled', onInstalled)
    setInstalled(window.matchMedia('(display-mode: standalone)').matches || Boolean((navigator as Navigator & { standalone?: boolean }).standalone))
    return () => { window.removeEventListener('beforeinstallprompt', onBeforeInstall); window.removeEventListener('appinstalled', onInstalled) }
  }, [])
  const installApp = async () => {
    if (!installPrompt) { alert('To install Mathata, use your browser menu and choose “Add to Home screen” or “Install Mathata”.'); return }
    await installPrompt.prompt()
    const choice = await installPrompt.userChoice
    if (choice.outcome === 'accepted') setInstalled(true)
    setInstallPrompt(null)
  }
  useEffect(() => { localStorage.setItem('mathata-fr', JSON.stringify({ blocks, deadlines, theme, backgroundImage, transparency })) }, [blocks, deadlines, theme, backgroundImage, transparency])
  useEffect(() => { try { const saved = JSON.parse(localStorage.getItem('mathata-fr') || '{}'); if (typeof saved.transparency === 'number') setTransparency(saved.transparency) } catch {} }, [])
  useEffect(() => { if (!pomodoroRunning) return; const timer = window.setInterval(() => setPomodoroSeconds(value => { if (value <= 1) { setPomodoroRunning(false); return 0 } return value - 1 }), 1000); return () => window.clearInterval(timer) }, [pomodoroRunning])
  const startPomodoro = (hours = pomodoroHours) => { setPomodoroHours(hours); setPomodoroSeconds(hours * 60 * 60); setPomodoroRunning(true) }
  const pausePomodoro = () => { if (pomodoroRunning) alert(pomodoroSeconds > 15 * 60 ? 'Bruhh ur kidding right' : 'Come on, you\'re almost there bud'); setPomodoroRunning(false) }
  const resetPomodoro = () => { setPomodoroRunning(false); setPomodoroSeconds(0) }
  const handleBackgroundUpload = (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !file.type.startsWith('image/')) return; const reader = new FileReader(); reader.onload = () => setBackgroundImage(String(reader.result)); reader.readAsDataURL(file); event.target.value = '' }
  const clearBackground = () => setBackgroundImage('')
  useEffect(() => { const t = setInterval(() => setNow(new Date()), 60000); return () => clearInterval(t) }, [])
  useEffect(() => { if ('serviceWorker' in navigator) navigator.serviceWorker.register('./sw.js').catch(() => undefined) }, [])

  const currentModule = (id: string) => MODULES.find(m => m.id === id)
  const toggleDone = (id: string) => setBlocks(items => items.map(b => b.id === id ? { ...b, done: !b.done } : b))
  const saveBlock = (next: Block) => { setBlocks(items => items.some(b => b.id === next.id) ? items.map(b => b.id === next.id ? next : b) : [...items, next]); setModal(undefined) }
  const deleteBlock = (id: string) => { setBlocks(items => items.filter(b => b.id !== id)); setModal(undefined) }
  const visibleDays = view === 'day' ? [day] : DAYS.map((_, i) => i)
  const plannedToday = blocks.filter(b => b.day === todayIndex && !b.locked)
  const visibleBlocks = blocks.filter(b => b.module === 'class' || b.module === 'all' || !hiddenModules.includes(b.module))
  const completed = blocks.filter(b => b.done).length
  const lineTop = now.getHours() >= 7 && now.getHours() <= 22 ? ((now.getHours() - 7) * 64 + now.getMinutes() * 64 / 60) : -100

  const glassStyle = { '--glass-opacity': `${transparency / 100}`, ...(backgroundImage ? { backgroundImage: `linear-gradient(rgba(250,250,249,${1 - transparency / 500}), rgba(250,250,249,${1 - transparency / 500})), url(${backgroundImage})` } : {}) } as React.CSSProperties
  return <div className={theme === 'dark' ? 'app dark' : 'app'} style={glassStyle}>
    <input ref={fileInputRef} className="sr-only" type="file" accept="image/png,image/jpeg,image/webp" onChange={handleBackgroundUpload} />
    <header className="appbar"><div className="brand"><div className="brand-mark" aria-label="Mathata logo">{DASH_LOGO}</div><div><strong>Mathata FR</strong><span>Study timetable</span></div></div><div className="header-actions"><button className="icon-button" aria-label="Change background" onClick={() => fileInputRef.current?.click()}><ImagePlus size={18} /></button>{!installed && <button className="install-button" onClick={installApp}><Download size={16} /> <span>Download app</span></button>}<button className="icon-button menu-button" aria-label="Open menu" onClick={() => setMenuOpen(!menuOpen)}><Menu size={20} /></button><button className="icon-button" aria-label="Open settings" onClick={() => setView('settings')}><Settings2 size={18} /></button><button className="icon-button" aria-label="Toggle theme" onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')}>{theme === 'light' ? <Moon size={18} /> : <Sun size={18} />}</button><button aria-label={editMode ? 'Done editing' : 'Edit timetable'} className={editMode ? 'primary-button editing' : 'primary-button'} onClick={() => setEditMode(!editMode)}><Pencil size={16} /> <span>{editMode ? 'Done editing' : 'Edit timetable'}</span></button><button className="primary-button" onClick={() => setModal(null)}><Plus size={17} /> <span>Add study block</span></button></div></header>
    <div className="shell">
      <aside className={menuOpen ? 'sidebar open' : 'sidebar'}><nav><NavItem active={view === 'week'} onClick={() => { setView('week'); setMenuOpen(false) }} icon={<CalendarDays size={18} />} label="Week" /><NavItem active={view === 'day'} onClick={() => { setView('day'); setMenuOpen(false) }} icon={<Clock3 size={18} />} label="Day" /><NavItem active={view === 'deadlines'} onClick={() => { setView('deadlines'); setMenuOpen(false) }} icon={<Target size={18} />} label="Deadlines" /><NavItem active={view === 'modules'} onClick={() => { setView('modules'); setMenuOpen(false) }} icon={<MoreHorizontal size={18} />} label="Modules" /><NavItem active={view === 'exam'} onClick={() => { setView('exam'); setMenuOpen(false) }} icon={<GraduationCap size={18} />} label="Exam prep" /><NavItem active={view === 'settings'} onClick={() => { setView('settings'); setMenuOpen(false) }} icon={<Settings2 size={18} />} label="Settings" /></nav><div className="sidebar-footer"><button className="secondary-button background-button" onClick={() => fileInputRef.current?.click()}><ImagePlus size={15} /> {backgroundImage ? 'Change background' : 'Add background'}</button>{backgroundImage && <button className="danger-button" onClick={clearBackground}>Remove background</button>}<div className="progress-label"><span>This week</span><strong>{completed}/{blocks.filter(b => !b.locked).length} done</strong></div><div className="progress"><i style={{ width: `${Math.round(completed / Math.max(1, blocks.filter(b => !b.locked).length) * 100)}%` }} /></div><p>Everything is saved on this device.</p></div></aside>
      <main className="main"><section className="welcome"><div><p className="eyebrow">{todayLabel}</p><h1>{view === 'week' ? 'Your week, in focus.' : view === 'day' ? `${DAYS[day]} at a glance.` : view === 'deadlines' ? 'Deadlines' : view === 'exam' ? "Let's prep for exam" : 'Your modules'}</h1></div><div className="week-controls">{(view === 'week' || view === 'day') && <><button className="small-button" onClick={() => setDay(todayIndex)}>Today</button><button className="icon-button" aria-label="Previous day" onClick={() => setDay((day + 6) % 7)}><ChevronLeft size={17} /></button><button className="icon-button" aria-label="Next day" onClick={() => setDay((day + 1) % 7)}><ChevronRight size={17} /></button></>}</div></section>
        {editMode && (view === 'week' || view === 'day') && <VisibilityPanel hiddenModules={hiddenModules} setHiddenModules={setHiddenModules} />}{view === 'week' || view === 'day' ? <CalendarView blocks={visibleBlocks} days={visibleDays} currentModule={currentModule} toggleDone={toggleDone} open={setModal} lineTop={lineTop} /> : view === 'deadlines' ? <Deadlines deadlines={deadlines} modules={MODULES} setDeadlines={setDeadlines} /> : view === 'exam' ? <ExamPrep examName={examName} setExamName={setExamName} examDate={examDate} setExamDate={setExamDate} examFocus={examFocus} setExamFocus={setExamFocus} /> : view === 'settings' ? <SettingsPanel theme={theme} setTheme={setTheme} transparency={transparency} setTransparency={setTransparency} backgroundImage={backgroundImage} upload={() => fileInputRef.current?.click()} clearBackground={clearBackground} /> : <Modules blocks={blocks} />}<Pomodoro hours={pomodoroHours} seconds={pomodoroSeconds} running={pomodoroRunning} started={pomodoroStarted} onStart={startPomodoro} onPause={pausePomodoro} onReset={resetPomodoro} />
      </main>
    </div>
    <nav className="bottom-tabs"><NavItem active={view === 'exam'} onClick={() => setView('exam')} icon={<GraduationCap size={18} />} label="Exam" /><NavItem active={view === 'week'} onClick={() => setView('week')} icon={<CalendarDays size={18} />} label="Week" /><NavItem active={view === 'day'} onClick={() => setView('day')} icon={<Clock3 size={18} />} label="Day" /><NavItem active={view === 'deadlines'} onClick={() => setView('deadlines')} icon={<Target size={18} />} label="Deadlines" /><NavItem active={view === 'modules'} onClick={() => setView('modules')} icon={<MoreHorizontal size={18} />} label="Modules" /></nav>
    {modal !== undefined && <Editor value={modal} onClose={() => setModal(undefined)} onSave={saveBlock} onDelete={deleteBlock} blocks={blocks} />}
  </div>
}

function NavItem({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) { return <button className={active ? 'nav-item active' : 'nav-item'} onClick={onClick}>{icon}<span>{label}</span></button> }
function CalendarView({ blocks, days, currentModule, toggleDone, open, lineTop }: { blocks: Block[]; days: number[]; currentModule: (id: string) => Module | undefined; toggleDone: (id: string) => void; open: (b: Block | null) => void; lineTop: number }) { return <div className="calendar-wrap"><div className="calendar-head"><div className="time-spacer" />{days.map(d => <div key={d} className={d === todayIndex ? 'day-head today' : 'day-head'}><span>{DAYS[d]}</span>{d === todayIndex && <b>Today</b>}</div>)}</div><div className="calendar-body"><div className="time-axis">{HOURS.map(h => <span key={h}>{pad(h)}:00</span>)}</div><div className="grid" style={{ gridTemplateColumns: `repeat(${days.length}, minmax(118px, 1fr))` }}>{days.map(d => <div className={d === todayIndex ? 'day-column today-column' : 'day-column'} key={d} onClick={(e) => { if (e.target === e.currentTarget) open({ id: crypto.randomUUID(), day: d, start: '09:00', end: '10:00', module: 'osc', topic: '' }) }}>{HOURS.map(h => <div className="hour-line" key={h} />)}{blocks.filter(b => b.day === d).map(b => { const [sh, sm] = b.start.split(':').map(Number); const [eh, em] = b.end.split(':').map(Number); const top = (sh - 7) * 64 + sm / 60 * 64; const height = Math.max(32, ((eh + em / 60) - (sh + sm / 60)) * 64); const mod = currentModule(b.module); return <div className={b.locked ? 'event locked' : `event ${b.done ? 'done' : ''}`} key={b.id} style={{ top, height, backgroundColor: mod?.color || '#78716c' }} onClick={(e) => { e.stopPropagation(); if (!b.locked) open(b) }}><button className="check" aria-label={b.done ? 'Mark not done' : 'Mark done'} onClick={(e) => { e.stopPropagation(); if (!b.locked) toggleDone(b.id) }}>{b.done && <Check size={12} />}</button><strong>{b.topic}</strong><span>{b.start}–{b.end}</span></div> })}{d === todayIndex && lineTop > 0 && <div className="current-line" style={{ top: lineTop }}><i /></div>}</div>)}</div></div></div> }
function Deadlines({ deadlines, modules, setDeadlines }: { deadlines: Deadline[]; modules: Module[]; setDeadlines: React.Dispatch<React.SetStateAction<Deadline[]>> }) { return <section className="content-panel"><div className="panel-head"><div><h2>Keep the important dates visible.</h2><p>Countdowns update automatically from today.</p></div><button className="secondary-button" onClick={() => { const title = prompt('Deadline name'); if (title) setDeadlines(d => [...d, { id: crypto.randomUUID(), title, module: 'osc', date: new Date().toISOString().slice(0, 10), kind: 'Assignment' }]) }}><Plus size={16} /> Add deadline</button></div><div className="deadline-list">{deadlines.map(d => { const mod = modules.find(m => m.id === d.module); const days = Math.ceil((new Date(d.date).getTime() - Date.now()) / 86400000); return <div className="deadline-row" key={d.id}><span className="module-dot" style={{ background: mod?.color }} /><div><strong>{d.title}</strong><span>{d.kind} · {new Date(d.date + 'T12:00:00').toLocaleDateString('en-GB', { day: 'numeric', month: 'short', year: 'numeric' })}</span></div><b>{days > 0 ? `${days} days` : days === 0 ? 'Today' : 'Passed'}</b><button className="icon-button" aria-label="Delete deadline" onClick={() => setDeadlines(items => items.filter(x => x.id !== d.id))}><Trash2 size={16} /></button></div> })}</div></section> }
function Modules({ blocks }: { blocks: Block[] }) { return <section className="module-grid">{MODULES.map(m => { const items = blocks.filter(b => b.module === m.id); const done = items.filter(b => b.done).length; return <article className="module-card" key={m.id}><div className="module-title"><span className="module-dot" style={{ background: m.color }} /><div><strong>{m.short}</strong><span>{m.name}</span></div><Settings2 size={16} /></div><div className="module-stats"><b>{items.length ? `${done}/${items.length}` : '0'} sessions</b><span>{done ? 'Good momentum' : 'Not started'}</span></div><div className="progress"><i style={{ background: m.color, width: `${items.length ? done / items.length * 100 : 0}%` }} /></div></article> })}</section> }

function VisibilityPanel({ hiddenModules, setHiddenModules }: { hiddenModules: string[]; setHiddenModules: React.Dispatch<React.SetStateAction<string[]>> }) { return <section className="visibility-panel"><div><span className="eyebrow">Edit mode</span><h2>Choose what you see</h2><p>Hide modules from your timetable without deleting their sessions.</p></div><div className="visibility-list">{MODULES.map(m => { const hidden = hiddenModules.includes(m.id); return <button key={m.id} className={hidden ? 'visibility-chip hidden' : 'visibility-chip'} onClick={() => setHiddenModules(items => hidden ? items.filter(id => id !== m.id) : [...items, m.id])}>{hidden ? <EyeOff size={15} /> : <Eye size={15} />}<span className="module-dot" style={{ background: m.color }} />{m.short}</button> })}</div></section> }

function ExamPrep({ examName, setExamName, examDate, setExamDate, examFocus, setExamFocus }: { examName: string; setExamName: (value: string) => void; examDate: string; setExamDate: (value: string) => void; examFocus: string; setExamFocus: (value: string) => void }) { const days = Math.max(0, Math.ceil((new Date(`${examDate}T12:00:00`).getTime() - Date.now()) / 86400000)); return <section className="exam-panel"><div className="exam-hero"><div className="exam-icon"><GraduationCap size={24} /></div><div><span className="eyebrow">Custom study timetable</span><h2>Let&apos;s prep for exam.</h2><p>Set the target, choose the modules, and build a rhythm you can actually keep.</p></div></div><div className="exam-form"><label>Plan name<input value={examName} onChange={e => setExamName(e.target.value)} /></label><label>Exam date<input type="date" value={examDate} onChange={e => setExamDate(e.target.value)} /></label><label>Modules to focus on<input value={examFocus} onChange={e => setExamFocus(e.target.value)} placeholder="OSC, FIS, BCS" /></label></div><div className="exam-plan"><div><span>Days remaining</span><strong>{days}</strong></div><div><span>Suggested rhythm</span><strong>2 focused blocks/day</strong></div><div><span>Plan status</span><strong>Ready to edit</strong></div></div><div className="exam-steps"><div><b>01</b><span>Review your weakest topics</span><small>Start with the modules you entered above.</small></div><div><b>02</b><span>Schedule focused blocks</span><small>Use Add study block to place them on the calendar.</small></div><div><b>03</b><span>Test and revisit</span><small>Mark sessions done as your confidence grows.</small></div></div></section> }

function SettingsPanel({ theme, setTheme, transparency, setTransparency, backgroundImage, upload, clearBackground }: { theme: 'light' | 'dark'; setTheme: (theme: 'light' | 'dark') => void; transparency: number; setTransparency: (value: number) => void; backgroundImage: string; upload: () => void; clearBackground: () => void }) { return <section className="settings-panel"><div className="settings-heading"><span className="eyebrow">Personalise your desk</span><h2>Make Mathata feel like yours.</h2><p>Choose a background, tune the glass, and let the app adapt its mood.</p></div><div className="settings-grid"><div className="setting-card"><div><strong>Appearance</strong><span>Theme and glass intensity</span></div><div className="theme-picker"><button className={theme === 'light' ? 'selected' : ''} onClick={() => setTheme('light')}><Sun size={16} /> Light</button><button className={theme === 'dark' ? 'selected' : ''} onClick={() => setTheme('dark')}><Moon size={16} /> Dark</button></div><label className="range-label">Glass transparency <b>{transparency}%</b><input type="range" min="35" max="92" value={transparency} onChange={e => setTransparency(Number(e.target.value))} /></label></div><div className="setting-card"><div><strong>Background</strong><span>{backgroundImage ? 'Your image is active' : 'Add a calm image or texture'}</span></div><button className="secondary-button" onClick={upload}><ImagePlus size={16} /> {backgroundImage ? 'Change image' : 'Choose image'}</button>{backgroundImage && <button className="danger-button" onClick={clearBackground}>Remove background</button>}<small>Your image stays on this device.</small></div></div></section> }
function Pomodoro({ hours, seconds, running, started, onStart, onPause, onReset }: { hours: number; seconds: number; running: boolean; started: boolean; onStart: (hours?: number) => void; onPause: () => void; onReset: () => void }) { const display = `${String(Math.floor(seconds / 3600)).padStart(2, '0')}:${String(Math.floor(seconds / 60) % 60).padStart(2, '0')}:${String(seconds % 60).padStart(2, '0')}`; return <section className="pomodoro-panel"><div><span className="eyebrow">Focus mode</span><h2>{started ? (running ? 'Study in progress.' : 'Paused for now.') : 'Ready when you are.'}</h2><p>{started ? 'Keep your promise to future you.' : 'Start study to begin a focused Pomodoro.'}</p></div>{started && <strong className="pomodoro-time">{display}</strong>}<div className="pomodoro-actions">{!started ? <><select aria-label="Study hours" value={hours} onChange={e => onStart(Number(e.target.value))}>{[1,2,3,4,5,6,7,8,9,10].map(h => <option key={h} value={h}>{h} hour{h > 1 ? 's' : ''}</option>)}</select><button className="primary-button" onClick={() => onStart(hours)}><Play size={15} /> Start study</button><button className="secondary-button" onClick={() => onStart(Math.floor(Math.random() * 10) + 1)}><Dice5 size={15} /> Not motivated</button></> : <><button className="secondary-button" onClick={onPause}>{running ? <Pause size={15} /> : <Play size={15} />} {running ? 'Pause' : 'Resume'}</button><button className="icon-button" aria-label="Reset Pomodoro" onClick={onReset}><RotateCcw size={16} /></button></>}</div></section> }
function Editor({ value, onClose, onSave, onDelete, blocks }: { value: Block | null; onClose: () => void; onSave: (b: Block) => void; onDelete: (id: string) => void; blocks: Block[] }) { const [form, setForm] = useState<Block>(value || { id: crypto.randomUUID(), day: todayIndex, start: '09:00', end: '10:00', module: 'osc', topic: '', notes: '' }); const set = (key: keyof Block, val: string | number) => setForm(f => ({ ...f, [key]: val })); const conflict = blocks.find(b => b.id !== form.id && b.day === form.day && b.module !== 'class' && form.start < b.end && form.end > b.start); const invalid = form.end <= form.start; return <div className="modal-backdrop" onMouseDown={onClose}><section className="editor" onMouseDown={e => e.stopPropagation()}><div className="editor-head"><div><p className="eyebrow">{value ? 'Edit study block' : 'New study block'}</p><h2>{value ? 'Shape the session.' : 'Make time for progress.'}</h2></div><button className="icon-button" aria-label="Close editor" onClick={onClose}><X size={20} /></button></div><label>Module<select value={form.module} onChange={e => set('module', e.target.value)}>{MODULES.map(m => <option key={m.id} value={m.id}>{m.short} · {m.name}</option>)}</select></label><label>Focus<input value={form.topic} placeholder="What will you work on?" onChange={e => set('topic', e.target.value)} /></label><div className="form-row"><label>Day<select value={form.day} onChange={e => set('day', Number(e.target.value))}>{DAYS.map((d, i) => <option key={d} value={i}>{d}</option>)}</select></label><label>Start<input type="time" step="900" value={form.start} onChange={e => set('start', e.target.value)} /></label><label>End<input type="time" step="900" value={form.end} onChange={e => set('end', e.target.value)} /></label></div><label>Notes <textarea value={form.notes || ''} placeholder="Optional notes" onChange={e => set('notes', e.target.value)} /></label>{invalid && <p className="form-error">End time must be after start time.</p>}{conflict && <p className="form-error">This overlaps with “{conflict.topic}”. Adjust the time or keep both intentionally.</p>}<div className="editor-actions">{value && <button className="danger-button" onClick={() => onDelete(form.id)}><Trash2 size={16} /> Delete block</button>}<span /><button className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={invalid || !form.topic.trim()} onClick={() => onSave(form)}>Save changes</button></div></section></div> }
